'use client';
import { useEffect, useState } from 'react';
import api from '@/lib/api';
import { RiskBadge, RiskBar } from '@/components/RiskBadge';

interface Hotspot {
  id: number; junction: string; zone: string;
  predicted_violations: number; historical_density: number;
  severity: number; risk_score: number; risk_level: string;
  forecast_datetime?: string; forecast_hour?: number;
}

function formatForecast(iso?: string) {
  if (!iso) return '—';
  const d = new Date(iso);
  return d.toLocaleString('en-IN', { day:'numeric', month:'short', hour:'numeric', minute:'2-digit', hour12:true });
}

export default function HotspotsPage() {
  const [hotspots,  setHotspots]  = useState<Hotspot[]>([]);
  const [loading,   setLoading]   = useState(true);
  const [sortField, setSortField] = useState<'risk_score'|'predicted_violations'|'forecast_datetime'>('forecast_datetime');
  const [filter,    setFilter]    = useState('All');

  useEffect(() => {
    api.get('/hotspots').then((r) => setHotspots(r.data)).finally(() => setLoading(false));
  }, []);

  const sorted = [...hotspots]
    .filter((h) => filter === 'All' || h.risk_level === filter)
    .sort((a, b) => {
      if (sortField === 'forecast_datetime') {
        return new Date(a.forecast_datetime || 0).getTime() - new Date(b.forecast_datetime || 0).getTime();
      }
      return (b as any)[sortField] - (a as any)[sortField];
    });

  return (
    <div>
      <div className="page-header">
        <div>
          <div className="page-title">Hotspot Prediction</div>
          <div className="page-subtitle">Hourly forecast for today, generated by the trained model</div>
        </div>
        <div style={{ fontSize:'0.95rem', color:'#555', fontWeight:600 }}>
          {hotspots.length} predicted events today
        </div>
      </div>

      <div style={{ padding:'1.8rem 2.2rem' }}>
        <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', marginBottom:'1.2rem' }}>
          <div style={{ display:'flex', gap:'2px' }}>
            {['All','Critical','High','Moderate','Low'].map((l) => (
              <button key={l} onClick={() => setFilter(l)} style={{
                padding:'0.5rem 1.1rem', fontSize:'0.88rem', letterSpacing:'0.06em',
                background: filter === l ? '#A0141E' : '#fff',
                color: filter === l ? '#F5F3EE' : '#111',
                border:'1px solid rgba(0,0,0,0.12)', cursor:'pointer',
                fontFamily:'inherit', fontWeight: filter === l ? 700 : 400,
              }}>{l}</button>
            ))}
          </div>
          <div style={{ display:'flex', alignItems:'center', gap:'0.6rem' }}>
            <span style={{ fontSize:'0.88rem', color:'#555', fontWeight:600 }}>Sort by:</span>
            {[{key:'forecast_datetime',label:'Time'},{key:'risk_score',label:'Risk Score'},{key:'predicted_violations',label:'Violations'}].map((s) => (
              <button key={s.key} onClick={() => setSortField(s.key as any)} style={{
                padding:'0.45rem 0.9rem', fontSize:'0.88rem',
                background: sortField === s.key ? '#160810' : '#fff',
                color: sortField === s.key ? '#F5F3EE' : '#111',
                border:'1px solid rgba(0,0,0,0.12)', cursor:'pointer',
                fontFamily:'inherit', fontWeight:600,
              }}>{s.label}</button>
            ))}
          </div>
        </div>

        <div className="section-card-v2">
          {loading ? (
            <div style={{ padding:'2.5rem', fontSize:'1rem', color:'#555' }}>Running prediction model...</div>
          ) : (
            <table className="data-table">
              <thead><tr>
                <th>#</th><th>Junction</th><th>Zone</th><th>Forecast Time</th>
                <th>Predicted Violations</th><th>Risk Score</th><th>Risk Level</th>
              </tr></thead>
              <tbody>
                {sorted.map((h, i) => (
                  <tr key={h.id}>
                    <td style={{ color:'#555', fontWeight:600 }}>{i + 1}</td>
                    <td style={{ fontWeight:600 }}>{h.junction}</td>
                    <td>{h.zone}</td>
                    <td style={{ fontWeight:600 }}>{formatForecast(h.forecast_datetime)}</td>
                    <td style={{ fontWeight:700 }}>{h.predicted_violations}</td>
                    <td><RiskBar score={h.risk_score} /></td>
                    <td><RiskBadge level={h.risk_level} /></td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  );
}
